name: OreEarn
version: 1.8.2
main: SchdowNVIDIA\OreEarn\Main
api: 5.0.0
authors:
  -  SchdowNVIDIA
  -  DragonfireHD98
description: "OreEarn plugin, earn money easily by mining ores."
depend:
  - BedrockEconomy
